/**
 * ErrorMessage.tsx — Styled error alert with dismiss button.
 *
 * Displays a human-readable error message returned by the API service
 * or generated by frontend validation.
 */

import React from 'react';
import type { ErrorMessageProps } from '../types/api';

const ErrorMessage: React.FC<ErrorMessageProps> = ({ message, onDismiss }) => {
  return (
    <div
      id="error-message"
      role="alert"
      className="flex items-start gap-3 p-4 rounded-xl border border-red-500/30 bg-red-950/40 backdrop-blur-sm animate-fade-in"
    >
      {/* Error icon */}
      <div className="flex-shrink-0 mt-0.5">
        <svg
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          className="w-5 h-5 text-red-400"
        >
          <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="1.5" />
          <path
            d="M12 7v6M12 17h.01"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
          />
        </svg>
      </div>

      {/* Content */}
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-red-300">Processing Error</p>
        <p className="text-sm text-red-400/80 mt-0.5 leading-relaxed">{message}</p>
      </div>

      {/* Dismiss button */}
      <button
        id="error-dismiss-button"
        onClick={onDismiss}
        className="flex-shrink-0 p-1 rounded-lg text-red-400 hover:text-red-200 hover:bg-red-900/40 transition-colors duration-150"
        aria-label="Dismiss error"
      >
        <svg
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          className="w-4 h-4"
        >
          <path d="M18 6L6 18M6 6l12 12" />
        </svg>
      </button>
    </div>
  );
};

export default ErrorMessage;
